--- #YAML:1.0
name:                Mail-LocalDelivery
version:             0.304
abstract:            Deliver mail to a local mailbox
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Email::Abstract:               0
    Errno:                         0
    Mail::Internet:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jose Alves de Castro <cog@cpan.org>
